Iar 60/create database and connect with backend
green-fox-academy/IceAge-Reddit-Backend pull request #3
Opened 2020-11-26 20:41 UTC by TomasBenes

Connection with database is set up

2020-11-26 22:14 UTC, JirinaGFA submitted a review, later dismissed
great, works!

2020-11-26 22:20 UTC, JirinaGFA commented on src/entities/User.ts
> +}
date_created is missing

2020-11-26 22:20 UTC, JirinaGFA requested changes
date_created in dtb is missing

2020-11-29 09:56 UTC, SimProch approved these changes
Make sure to incorporate Jirinka's requested changes

2020-11-29 10:38 UTC, JirinaGFA approved these changes

2020-11-29 11:50 UTC, merged